
#define NTK_GUI 1
#define VSTAUDIOOUT 1

#define PIXMAP_PATH "/usr/share/zynaddsubfx/pixmaps/"
#define SOURCE_DIR  "/usr/share/zynaddsubfx/pixmaps/nothing-here"

// zynaddsubfx includes
#include "zynaddsubfx/DSP/AnalogFilter.cpp"
#include "zynaddsubfx/DSP/FFTwrapper.cpp"
#include "zynaddsubfx/DSP/Filter.cpp"
#include "zynaddsubfx/DSP/FormantFilter.cpp"
#include "zynaddsubfx/DSP/SVFilter.cpp"
#include "zynaddsubfx/DSP/Unison.cpp"
#include "zynaddsubfx/Effects/Alienwah.cpp"
#include "zynaddsubfx/Effects/Chorus.cpp"
#include "zynaddsubfx/Effects/Distorsion.cpp"
#include "zynaddsubfx/Effects/DynamicFilter.cpp"
#include "zynaddsubfx/Effects/Echo.cpp"
#include "zynaddsubfx/Effects/Effect.cpp"
#include "zynaddsubfx/Effects/EffectLFO.cpp"
#include "zynaddsubfx/Effects/EffectMgr.cpp"
#include "zynaddsubfx/Effects/EQ.cpp"
#include "zynaddsubfx/Effects/Phaser.cpp"
#include "zynaddsubfx/Effects/Reverb.cpp"
#include "zynaddsubfx/Misc/Bank.cpp"
#include "zynaddsubfx/Misc/Config.cpp"
#include "zynaddsubfx/Misc/Dump.cpp"
#include "zynaddsubfx/Misc/Master.cpp"
#include "zynaddsubfx/Misc/Microtonal.cpp"
#include "zynaddsubfx/Misc/Part.cpp"
#include "zynaddsubfx/Misc/Recorder.cpp"
//#include "zynaddsubfx/Misc/Stereo.cpp"
#include "zynaddsubfx/Misc/Util.cpp"
#include "zynaddsubfx/Misc/WavFile.cpp"
#include "zynaddsubfx/Misc/WaveShapeSmps.cpp"
#include "zynaddsubfx/Misc/XMLwrapper.cpp"
#include "zynaddsubfx/Nio/AudioOut.cpp"
#include "zynaddsubfx/Nio/Engine.cpp"
#include "zynaddsubfx/Nio/EngineMgr.cpp"
//#include "zynaddsubfx/Nio/MidiIn.cpp"
#include "zynaddsubfx/Nio/Nio.cpp"
#include "zynaddsubfx/Nio/NulEngine.cpp"
#include "zynaddsubfx/Nio/InMgr.cpp"
#include "zynaddsubfx/Nio/OutMgr.cpp"
#include "zynaddsubfx/Nio/WavEngine.cpp"
#include "zynaddsubfx/Params/ADnoteParameters.cpp"
#include "zynaddsubfx/Params/Controller.cpp"
#include "zynaddsubfx/Params/EnvelopeParams.cpp"
#include "zynaddsubfx/Params/FilterParams.cpp"
#include "zynaddsubfx/Params/LFOParams.cpp"
#include "zynaddsubfx/Params/PADnoteParameters.cpp"
#include "zynaddsubfx/Params/Presets.cpp"
#include "zynaddsubfx/Params/PresetsArray.cpp"
#include "zynaddsubfx/Params/PresetsStore.cpp"
#include "zynaddsubfx/Params/SUBnoteParameters.cpp"
#include "zynaddsubfx/Synth/ADnote.cpp"
#include "zynaddsubfx/Synth/Envelope.cpp"
#include "zynaddsubfx/Synth/LFO.cpp"
#include "zynaddsubfx/Synth/OscilGen.cpp"
#include "zynaddsubfx/Synth/PADnote.cpp"
#include "zynaddsubfx/Synth/Resonance.cpp"
#include "zynaddsubfx/Synth/SUBnote.cpp"
#include "zynaddsubfx/Synth/SynthNote.cpp"

#ifdef WANT_ZYNADDSUBFX_GUI
# include "zynaddsubfx/UI/NioUI.h"
# include "zynaddsubfx/UI/ADnoteUI.cc"
# include "zynaddsubfx/UI/BankUI.cc"
# include "zynaddsubfx/UI/ConfigUI.cc"
# include "zynaddsubfx/UI/EffUI.cc"
# include "zynaddsubfx/UI/EnvelopeUI.cc"
# include "zynaddsubfx/UI/FilterUI.cc"
# include "zynaddsubfx/UI/LFOUI.cc"
# include "zynaddsubfx/UI/MasterUI.cc"
# include "zynaddsubfx/UI/MicrotonalUI.cc"
# include "zynaddsubfx/UI/OscilGenUI.cc"
# include "zynaddsubfx/UI/PADnoteUI.cc"
# include "zynaddsubfx/UI/PartUI.cc"
# include "zynaddsubfx/UI/PresetsUI.cc"
# include "zynaddsubfx/UI/ResonanceUI.cc"
# include "zynaddsubfx/UI/SUBnoteUI.cc"
# include "zynaddsubfx/UI/VirKeyboard.cc"
# include "zynaddsubfx/UI/WidgetPDial.cpp"
# include "zynaddsubfx/UI/NioUI.cpp"
#endif
