#!/bin/bash
# Script to bridge/start pulseaudio into JACK mode

INSTALL_PREFIX="X-PREFIX-X"

# ----------------------------------------------

if [ ! -d ~/.pulse ]; then
    mkdir -p ~/.pulse
fi

if [ ! -f ~/.pulse/client.conf ]; then
    echo "autospawn = no" > ~/.pulse/client.conf
else
    if (! cat ~/.pulse/client.conf | grep "autospawn = no" > /dev/null); then
        sed -i '/autospawn =/d' ~/.pulse/client.conf
        echo "autospawn = no" >> ~/.pulse/client.conf
    fi
fi

if [ ! -f ~/.pulse/daemon.conf ]; then
    echo "default-sample-format = float32le" > ~/.pulse/daemon.conf
    echo "realtime-scheduling = yes" >> ~/.pulse/daemon.conf
    echo "rlimit-rttime = -1" >> ~/.pulse/daemon.conf
    echo "exit-idle-time = -1" >> ~/.pulse/daemon.conf
else
    if (! cat ~/.pulse/daemon.conf | grep "default-sample-format = float32le" > /dev/null); then
        sed -i '/default-sample-format = /d' ~/.pulse/daemon.conf
        echo "default-sample-format = float32le" >> ~/.pulse/daemon.conf
    fi
    if (! cat ~/.pulse/daemon.conf | grep "realtime-scheduling = yes" > /dev/null); then
        sed -i '/realtime-scheduling = /d' ~/.pulse/daemon.conf
        echo "realtime-scheduling = yes" >> ~/.pulse/daemon.conf
    fi
    if (! cat ~/.pulse/daemon.conf | grep "rlimit-rttime = -1" > /dev/null); then
        sed -i '/rlimit-rttime =/d' ~/.pulse/daemon.conf
        echo "rlimit-rttime = -1" >> ~/.pulse/daemon.conf
    fi
    if (! cat ~/.pulse/daemon.conf | grep "exit-idle-time = -1" > /dev/null); then
        sed -i '/exit-idle-time =/d' ~/.pulse/daemon.conf
        echo "exit-idle-time = -1" >> ~/.pulse/daemon.conf
    fi
fi

# ----------------------------------------------

PLAY_ONLY=false
STEREO_ONLY=false

for arg in "$@";do
    case "$arg" in
        -h|--h|--help)
    echo "usage: $0 [command]

    -p, --play    Playback mode only
    -s, --stereo  Stereo only

    -h, --help    Show this help menu
        --dummy   Don't do anything, just create the needed files

    NOTE:
    When runned with no arguments, pulse2jack will
    activate PulseAudio with both playback and record modes.
    "
    exit
        ;;

        --dummy)
    exit
        ;;

        -p|--p|--play)
    PLAY_ONLY=true
#     FILE=$INSTALL_PREFIX/share/cadence/pulse2jack/play.pa
        ;;
        
        -s|--s|--stereo)
    STEREO_ONLY=true
        ;;

# 
#         *)
#     FILE=$INSTALL_PREFIX/share/cadence/pulse2jack/play+rec.pa
#         ;;
    esac
done

FILE=$INSTALL_PREFIX/share/cadence/pulse2jack/play+rec.pa

if [ "$PLAY_ONLY" && "$STEREO_ONLY" ];then
    FILE=$INSTALL_PREFIX/share/cadence/pulse2jack/play_stereo.pa
elif [ "$PLAY_ONLY" ];then
    FILE=$INSTALL_PREFIX/share/cadence/pulse2jack/play.pa
elif [ "$STEREO_ONLY" ];then
    FILE=$INSTALL_PREFIX/share/cadence/pulse2jack/play+rec_stereo.pa
else
    FILE=$INSTALL_PREFIX/share/cadence/pulse2jack/play+rec.pa
fi

# ----------------------------------------------

IsPulseAudioRunning()
{
    PROCESS=`ps -u $USER | grep pulseaudio`
    if [ "$PROCESS" == "" ]; then
        false
    else
        true
    fi
}

if (IsPulseAudioRunning); then
{
    if (`jack_lsp | grep "PulseAudio JACK Sink:" > /dev/null`); then
    {
        echo "PulseAudio is already running and bridged to JACK"
    }
    else
    {
        echo "PulseAudio is already running, bridge it..."

        if [ "$PLAY_ONLY" ]; then
        {
            if [ "$STEREO_ONLY" ];then
                pactl load-module module-jack-sink channels=2 > /dev/null
            else
                pactl load-module module-jack-sink > /dev/null
            fi
            
            pacmd set-default-source jack_in > /dev/null
        }
        else
        {
            if [ "$STEREO_ONLY" ];then
                pactl load-module module-jack-sink channels=2   > /dev/null
                pactl load-module module-jack-source channels=2 > /dev/null
            else
                pactl load-module module-jack-sink   > /dev/null
                pactl load-module module-jack-source > /dev/null
            fi
            
            pacmd set-default-sink jack_out > /dev/null
            pacmd set-default-source jack_in > /dev/null
        }
        fi

        echo "Done"
    }
    fi
}
else
{
    if (`pulseaudio --daemonize --high-priority --realtime --exit-idle-time=-1 --file=$FILE -n`); then
        echo "Initiated PulseAudio successfully!"
    else
        echo "Failed to initialize PulseAudio!"
    fi
}
fi
