#!/bin/bash
# Script to bridge/start pulseaudio into JACK mode

INSTALL_PREFIX="X-PREFIX-X"

# ----------------------------------------------

if [ ! -d ~/.pulse ]; then
    mkdir -p ~/.pulse
fi

# ----------------------------------------------

PLAY_ONLY="no"

case $1 in
    -h|--h|--help)
echo "usage: $0 [command]

  -p, --play    Playback mode only

  -h, --help    Show this help menu
      --dummy   Don't do anything, just create the needed files

NOTE:
 When runned with no arguments, pulse2jack will
 activate PulseAudio with both playback and record modes.
"
exit
    ;;

    --dummy)
exit
    ;;

    -p|--p|--play)
PLAY_ONLY="yes"
FILE=$INSTALL_PREFIX/share/cadence/pulse2jack/play.pa
    ;;

    *)
FILE=$INSTALL_PREFIX/share/cadence/pulse2jack/play+rec.pa
    ;;
esac

# ----------------------------------------------

IsPulseAudioRunning()
{
    PROCESS=`ps -u $USER | grep pulseaudio`
    if [ "$PROCESS" == "" ]; then
        false
    else
        true
    fi
}

if (IsPulseAudioRunning); then
{
    if (`jack_lsp | grep "PulseAudio JACK Sink:" > /dev/null`); then
    {
        echo "PulseAudio is already running and bridged to JACK"
    }
    else
    {
        echo "PulseAudio is already running, bridge it..."

        if [ "$PLAY_ONLY" == "yes" ]; then
        {
            pactl load-module module-jack-sink > /dev/null
            pacmd set-default-source jack_in > /dev/null
        }
        else
        {
            pactl load-module module-jack-sink > /dev/null
            pactl load-module module-jack-source > /dev/null
            pacmd set-default-sink jack_out > /dev/null
            pacmd set-default-source jack_in > /dev/null
        }
        fi

        echo "Done"
    }
    fi
}
else
{
    if (`pulseaudio --daemonize=no --log-target=journal`); then
        echo "Initiated PulseAudio successfully!"
    else
        echo "Failed to initialize PulseAudio!"
    fi
}
fi
