#!/bin/bash

if [ -f /usr/bin/python3 ]; then
  PYTHON=/usr/bin/python3
else
  PYTHON=python
fi

INSTALL_PREFIX="X-PREFIX-X"

if [ $1 == "--system-start-by-x11-startup" ]; then
  $PYTHON $INSTALL_PREFIX/share/cadence/src/cadence_session_start.py --system-start &
  exec $2
else
  exec $PYTHON $INSTALL_PREFIX/share/cadence/src/cadence_session_start.py "$@"
fi
