#!/bin/bash

if [ -f /usr/bin/python3 ]; then
  PYTHON=/usr/bin/python3
else
  PYTHON=python
fi

INSTALL_PREFIX="X-PREFIX-X"

if [ "$1"x == "--system-start-by-x11-startup"x ]; then
  $PYTHON $INSTALL_PREFIX/share/cadence/src/cadence_session_start.py --system-start &
  shift
  exec "$@"
else
  exec $PYTHON $INSTALL_PREFIX/share/cadence/src/cadence_session_start.py "$@"
fi
