#!/bin/bash

if [ -f /usr/bin/python3 ]; then
  PYTHON=/usr/bin/python3
else
  PYTHON=python
fi

INSTALL_PREFIX="X-PREFIX-X"

if [ "$1"x == "--system-start-by-x11-startup"x ]; then
  # called via $STARTUP in 21cadence-session-inject
  $PYTHON $INSTALL_PREFIX/share/cadence/src/cadence_session_start.py --system-start &
  shift
  if [ "$1"x != ""x ]; then
    exec "$@"
  else
    exec x-session-manager
  fi
elif [ "$1"x == "--maybe-system-start"x ]; then
  # called via autostart cadence-session-start.desktop
  # only do something if 21cadence-session-inject was ignored
  if [ "$CADENCE_AUTO_STARTED"x == ""x ]; then
    exec $PYTHON $INSTALL_PREFIX/share/cadence/src/cadence_session_start.py --system-start
  fi
else
  # called by user
  exec $PYTHON $INSTALL_PREFIX/share/cadence/src/cadence_session_start.py "$@"
fi
