.TH SORD_VALIDATE 1 "21 Mar 2012"

.SH NAME
.B sord_validate \- Validate RDF data

.SH SYNOPSIS
sord_validate [OPTION]... INPUT...

This is a simple validator which checks that all used properties are actually
defined, and that the domain and range of properties is explicitly correct.
Note that an "error" from this program does not necessarily mean data is
invalid, since it is not required to explicitly list types in RDF, however it
is a good idea to do so.  If data type definitions are available with an
xsd:pattern property, literals with that datatype will be checked against the
xsd:pattern (a regular expresssion) to ensure they are valid.

This program does not retrieve any data from the web or magical places on the
file system.  It only processes files passed directly on the command line.
This means you must pass all used vocabularies to get a useful result.
        
.SH AUTHOR
sord_validate was written by David Robillard <d@drobilla.net>

.SH COPYRIGHT
Copyright \(co 2012 David Robillard.
.br
License: <http://www.opensource.org/licenses/isc-license>
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.

.SH "SEE ALSO"
<http://drobilla.net/software/sord>
